REM https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/deploy-ramdisk-ironic.initramfs
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/deploy-ramdisk-ironic.kernel 
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/deploy-ramdisk-ironic.tar
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/ironic-python-agent.initramfs
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/ironic-python-agent.kernel
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/ironic-python-agent.tar
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/ironic-python-agent.vmlinuz
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/overcloud-full.initrd
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/overcloud-full.qcow2
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/overcloud-full.tar
wget https://repos.fedorapeople.org/repos/openstack-m/rdo-images-centos-liberty/overcloud-full.vmlinuz
