resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/tripleo/mycloud_34/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:      /home/stack/tripleo/mycloud_34/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig:   /home/stack/tripleo/mycloud_34/nic-configs/controller_ext.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/tripleo/mycloud_34/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig:  /home/stack/tripleo/mycloud_34/nic-configs/ceph-storage.yaml

parameter_defaults:
  # Customize all these values to match the local environment
  InternalApiNetCidr: 10.10.10.0/24
  StorageNetCidr: 10.20.20.0/24
  StorageMgmtNetCidr: 10.30.30.0/24
  TenantNetCidr: 10.40.40.0/24
  ExternalNetCidr: 192.168.3.0/24
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: "24"
  InternalApiAllocationPools: [{'start': '10.10.10.10', 'end': '10.10.10.200'}]
  StorageAllocationPools: [{'start': '10.20.20.10', 'end': '10.20.20.200'}]
  StorageMgmtAllocationPools: [{'start': '10.30.30.10', 'end': '10.30.30.200'}]
  TenantAllocationPools: [{'start': '10.40.40.10', 'end': '10.40.40.200'}]
  # Use an External allocation pool which will leave room for floating IPs
  ExternalAllocationPools: [{'start': '192.168.3.70', 'end': '192.168.3.90'}]
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 192.168.3.1
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.2.1
  # Generally the IP of the Undercloud
  EC2MetadataIp: 192.0.2.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["192.168.2.2","8.8.8.8"]
  InternalApiNetworkVlanID: 10
  StorageNetworkVlanID: 20
  StorageMgmtNetworkVlanID: 30
  TenantNetworkVlanID: 40
  # ExternalNetworkVlanID: 50
  # May set to br-ex if using floating IPs only on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
  # Customize bonding options if required (ignored if bonds are not used)
#  BondInterfaceOvsOptions:
#      "bond_mode=balance-tcp lacp=active other-config:lacp-fallback-ab=true"
  
